#!/bin/bash
# check if affinity works

testdir=`dirname "$0"`
: ${srcdir:=${testdir}/..}
: ${builddir:=${srcdir}}
export PATH=${builddir}:$PATH

S=`nusactl --show | grep nodebind:`
NODES=`echo $S | sed -e "s/nodebind://"`

S=`nusactl --show | grep physcpubind:`
CPUS=`echo $S | sed -e "s/physcpubind://"`

for i in $CPUS ; do
    if [ "$(nusactl --physcpubind=$i "${testdir}"/printcpu)" != "$i" ] ; then
       echo "--physcpubind for $i doesn't work"
       exit 1
    fi
    if [ "$(nusactl --physcpubind=$i nusactl --show | awk '/^physcpubind/ { print $2 }' )" != "$i" ] ; then
	echo "--show doesn't agree with physcpubind for cpu $i"
	exit 1
    fi
done

for i in $NODES ; do
    if [ $(nusactl --cpunodebind=$i nusactl --show | awk '/nodebind/ { print $2 }' ) != $i ] ; then
	echo "--show doesn't agree with cpunodebind for node $i"
	exit 1
    fi
done
